name: Android CI

on:
  workflow_call:  # Only reusable
  workflow_dispatch:  # Allow manual trigger for debugging

jobs:
  unit-tests:
    uses: ./.github/workflows/android-unit-tests.yml

  # instrumented-tests:
  #   uses: ./.github/workflows/android-instrumented-tests.yml
