name: Android CI/CD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/android-ci.yml

  cd:
    name: Continuous Deployment
    needs: ci
    if: success() && github.ref == 'refs/heads/master'
    uses: ./.github/workflows/android-cd.yml
    secrets: inherit
