name: Android CD

on:
  workflow_call:  # Only reusable
  workflow_dispatch:  # Allow manual trigger for debugging

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: "platform-tools build-tools;35.0.0 platforms;android-35"
          accept-android-sdk-licenses: true

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release.jks
          echo "Keystore file created:"
          ls -la app/release.jks
          echo "Keystore file type:"
          file app/release.jks
          echo "Keystore info:"
          keytool -list -keystore app/release.jks -storepass "${{ secrets.SIGNING_STORE_PASSWORD }}" || echo "Failed to read keystore"

      - name: Build release APK
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_STORE_FILE: ${{ github.workspace }}/app/release.jks

      - name: Clean up keystore
        if: always()
        run: rm -f app/release.jks

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            app/build/outputs/apk/release/
            app/build/reports/
          retention-days: 30
